name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.23', '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@bc5b3be6386c117ea5347415320d799cd77c6ee6
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
